feature/P2022-105
intive/patronage22-eganortap pull request #12
Opened 2022-02-16 18:32 UTC by doomedcat17

Some info for reviewers:
- You can easily deploy postgres instance as a docker container by executing `docker-compose up -d` inside project root directory (*docker-compose required*).
- Default `application.properties` does not contain database properties, so use `application-dev.properties` instead
(edit run configuration in Intelij and add `dev` profile or add `-Dspring.profiles.active=dev` as VM option). 
- If you want to initialize databse schema by Hibernate, add `spring.jpa.hibernate.ddl-auto=create` inside 
`application-dev.properties`.
**Keep in mind, that previous data will be gone.**
I decided not to include that property to avoid potential damage of leaving it there.

2022-02-16 20:14 UTC, jasokolowska commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @Column(name = "PK_id", updatable = false, nullable = false)
shouldnt be in @GeneratedValue also name of the sequence?

2022-02-17 15:35 UTC, doomedcat17 commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @Column(name = "PK_id", updatable = false, nullable = false)
Yup, my bad

2022-02-17 16:55 UTC, jasokolowska approved these changes
Looks fine

2022-02-20 16:15 UTC, Pawel-Koz approved these changes

2022-02-20 18:23 UTC, jasokolowska approved these changes

2022-02-21 06:46 UTC, jasokolowska approved these changes

2022-02-21 08:35 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +
implements Serializable but where is verionId?

2022-02-21 08:35 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @Column(name = "PK_id", updatable = false, nullable = false)
incorrect name `PK_id`

2022-02-21 08:36 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +
remove spaces between attrs

2022-02-21 08:36 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    private List<Question> questions;
eager fetching

2022-02-21 08:36 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +        return getClass().hashCode();
think about hashcode, is it good enought?

2022-02-21 08:37 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/PossibleAnswer.java
> +public class PossibleAnswer implements Serializable {
the same Serializable but not completed

2022-02-21 08:37 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/PossibleAnswer.java
> +    @SequenceGenerator(name = "possible_answer_gen", sequenceName = "possible_answer_seq")
why other sequence? is it make a sence?

2022-02-21 08:37 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/PossibleAnswer.java
> +    private Question question;
eager

2022-02-21 08:37 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/PossibleAnswer.java
> +        return getClass().hashCode();
the same

2022-02-21 08:37 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Question.java
> +
the same

2022-02-21 08:38 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Question.java
> +    @SequenceGenerator(name = "question_gen", sequenceName = "question_seq")
the same

2022-02-21 08:38 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Question.java
> +    @Column(name = "PK_id", updatable = false, nullable = false)
the same

2022-02-21 08:38 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Question.java
> +    private Poll poll;
the same name and eager

2022-02-21 08:38 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Question.java
> +    private Set<UserAnswer> userAnswers;
the same

2022-02-21 08:38 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Question.java
> +    private Set<PossibleAnswer> possibleAnswers;
the same, are u sure cascade for all? is it good?

2022-02-21 08:38 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Question.java
> +        return getClass().hashCode();
+1

2022-02-21 08:39 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +public class UserAnswer implements Serializable {
+1

2022-02-21 08:39 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_answer_gen")
+1

2022-02-21 08:39 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +    @Column(name = "PK_id", updatable = false, nullable = false)
+1

2022-02-21 08:39 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +    @JoinColumn(name = "FK_Question_id")
+1

2022-02-21 08:39 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +    private PossibleAnswer possibleAnswer;
+1

2022-02-21 08:39 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +        return getClass().hashCode();
+1

2022-02-21 08:40 UTC, eveento commented on src/main/resources/application-dev.properties
> +spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
where is prod?

2022-02-21 08:41 UTC, eveento commented on src/test/java/com/intive/patronage22eganortap/RepositoryLayerTest.java
> +class RepositoryLayerTest {
these tests make non sence? why are u testing hibernate? in your opinion hibernate is not well enough tested?

2022-02-21 08:41 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    private String email;
no validation

2022-02-21 08:42 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    private Date creationDate;
incorrect data type

2022-02-21 08:42 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    private Date startDate;
the same

2022-02-21 08:42 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    private String status;
incorrect data type

2022-02-21 08:43 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Question.java
> +    private Poll poll;
change value name for pollId. JoinColumn name is terrible

2022-02-21 08:44 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +    private String sessionId;
sessionId like a string?

2022-02-21 08:44 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +    @JoinColumn(name = "FK_Possible_answers_id")
name...

2022-02-21 09:30 UTC, piotrekkrzywicki requested changes
1. Dont use user postgres for other activities than creating proper user and DB creation (defined for docker image).
2. Naming is terrible (snake_case shall be used).
3.  Look and collections. Eager in many cases is better approach.

2022-02-21 09:30 UTC, piotrekkrzywicki commented on src/main/java/com/intive/patronage22eganortap/domain/PossibleAnswer.java
> +        return id != null && this.id.equals(possibleAnswer.getId());
instead obj != null  use Objects.nonNull(obj), instead obj == null use Objects.isNull

2022-02-22 12:04 UTC, doomedcat17 commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @Column(name = "PK_id", updatable = false, nullable = false)
I thought names from the schema are correct ;-;

2022-02-22 12:15 UTC, doomedcat17 commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    private List<Question> questions;
OneToMany is not fetched lazily by default?  ;-;
https://jakarta.ee/specifications/persistence/2.2/apidocs/javax/persistence/onetomany

2022-02-22 12:16 UTC, doomedcat17 commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    private String status;
I was sticking to what was in the schema ;-;

2022-02-22 15:54 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +    @JoinColumn(name = "FK_Possible_answers_id")
eager

2022-02-22 15:56 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    private String status;
type on db are diff then type in java. There are no e.g. LocalDateTime or enums.... But in Java you have much more possibilities to resolve it

2022-02-24 16:56 UTC, piotrekkrzywicki commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +        return Objects.hashCode(id);
only id is not enough (maybe multiplied by someconstant prime number)

2022-02-24 17:00 UTC, piotrekkrzywicki commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    private URL link;
String?

2022-02-24 17:28 UTC, piotrekkrzywicki commented on docker-compose.yaml
> +      - ./src/main/resources:/docker-entrypoint-initdb.d/
try different solution instead adding whole folder.

question - if we shall keep it in /docker-entrypoint-initdb.d/

2022-02-24 17:43 UTC, piotrekkrzywicki commented
Show sql on dev spring profile

2022-03-03 08:14 UTC, eveento reviewed
needs work

2022-03-03 08:14 UTC, eveento commented on src/main/resources/application-dev.properties
> +spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
konfiguracja jest niewystarczajaca. Czas powinien byc podany jako Europe/Warsaw. brak profilu produkcyjnego i wylaczonego na nim generowania encji. produkcyjnie sql nie powinny sie drukowac. czesci wspiolne mozna wyniesc do domyslnego pliku a profile moga po nim dziedziczyc. nie ma ustawionego poll-size, idle lifetime, leak-detection dla np. hikari. jest to podstawowa konfiguracja ktora powinna byc. dodatkowo hibernate moze miec cos takiego jak strategie ktore tez nie sa ustawione.generate-ddl oraz ddl-auto powinny sie rowniez znalezc tu.

2022-03-03 08:14 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/PossibleAnswer.java
> +        return Objects.hashCode(id) * 2;
skad bierzesz te wartosci? a co jesli sie one powtorza. moze pomyslmy nad interface w ktorym moglibysmy je 3mac?

2022-03-03 08:14 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/PossibleAnswer.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "possible_answer_gen")
nie jestem zwolennikiem kazdej jednej sekwencji dla kazdej tabeli. jesli przewidujesz fakt ze danych bedzie tutaj na tyle duzo przekrecisz licznik Long to ma to sens. Jednak tylko i wylacznie w takim przypadku ma to sens

2022-03-03 08:18 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/PossibleAnswer.java
> +        if (Objects.isNull(o) || !this.getClass().equals(o.getClass())) return false;
this.getClass().equals(o.getClass()) mozesz zamienic uzywajac instanceof

2022-03-04 10:26 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @CreationTimestamp
jestes pewny ze ta annotacja powinna tu byc? https://docs.jboss.org/hibernate/orm/4.3/javadocs/org/hibernate/annotations/CreationTimestamp.html

2022-03-04 10:26 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @NotBlank
@email oraz @NotBlank czy to ma sens?

2022-03-04 10:30 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @CreationTimestamp
https://docs.jboss.org/hibernate/orm/4.3/javadocs/org/hibernate/annotations/CreationTimestamp.html

upewnijmy sie ze dla LocalDateTime bedzie to dzialac poprawnie

2022-03-04 15:22 UTC, doomedcat17 commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @CreationTimestamp
To są docsy do wersji 4.3, a działamy na 5.6
https://docs.jboss.org/hibernate/orm/5.6/javadocs/org/hibernate/annotations/CreationTimestamp.html

2022-03-04 15:24 UTC, doomedcat17 commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @CreationTimestamp
Sprawdzałem i dodawał timestamp do rekordu, więc chyba jest ok

2022-03-05 13:11 UTC, doomedcat17 commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @NotBlank
https://docs.jboss.org/hibernate/beanvalidation/spec/2.0/api/javax/validation/constraints/Email.html
_null elements are considered valid._
Pusty String też jest traktowany jako valid, czego raczej nie chcemy.

2022-03-06 17:46 UTC, eveento reviewed
need works

2022-03-06 17:46 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/config/DatasourceConfig.java
> +@Profile("!test")
co to jest? tak nie powinno sie robic

2022-03-06 17:46 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/config/DatasourceConfig.java
> +public class DatasourceConfig {
nie o to chodzilo w laczeniu aliasow, da sie to zrobic w 4 linijkach w application.properties

2022-03-06 17:46 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @NotBlank
jaki jest sens notBlank i email ? czy email nie zalatwim nam tego?

2022-03-06 17:46 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @Min(0)
podbijam

2022-03-06 17:46 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    @OneToMany(cascade = {CascadeType.PERSIST, CascadeType.DETACH, CascadeType.MERGE, CascadeType.REFRESH},
usuwasz dziecko a nie masz kaskady na usuwanie?

2022-03-06 17:46 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/PossibleAnswer.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "possible_answer_gen")
nadal sa rozne sekwencje

2022-03-06 17:46 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Question.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "question_gen")
inne sekwencje

2022-03-06 17:46 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Question.java
> +    @OneToMany(cascade = {CascadeType.PERSIST, CascadeType.DETACH, CascadeType.REFRESH, CascadeType.MERGE},
orphanRemoval bez kaskady na usunieciu. Dlaczego tak?

2022-03-06 17:46 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/UserAnswer.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_answer_gen")
to samo

2022-03-06 17:46 UTC, eveento commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +{
co to jest?

2022-03-06 17:46 UTC, eveento commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.jdbc.time_zone=CET
czy timezone jest ok ?

2022-03-06 17:46 UTC, eveento commented on src/main/resources/application.properties
> +spring.datasource.hikari.leak-detection-threshold=5000
chyba za male wartosci

2022-03-06 18:06 UTC, eveento reviewed
needs works

2022-03-06 18:06 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +    private boolean isPublic;
thinks about default values. take notes for builder

2022-03-07 19:06 UTC, doomedcat17 commented on src/main/java/com/intive/patronage22eganortap/domain/Poll.java
> +
@Validated annotation is part of org.springframework.validation and it's not related to hibernate-validator, which is used to validate entities. It works fine

2022-03-08 11:51 UTC, eveento commented on src/main/resources/application.properties
> +spring.profiles.active=prod
to powinno byc w profilo prod, a nie default

2022-03-08 15:02 UTC, doomedcat17 commented on src/main/resources/application.properties
> +spring.profiles.active=prod
To nie będzie działać. `spring.profiles.active` można umieścić jedynie w defaultowych properties (Spring Boot 2.4+).
Chyba, że damy `spring.config.use-legacy-processing=true`, to wtedy przejdzie.

2022-03-10 14:36 UTC, merged