P2022-10: add Springdoc-openapi dependencies, add swagger annotations…
intive/patronage22-eganortap pull request #14
Opened 2022-02-22 14:26 UTC by Pawel-Koz

To view endpoints in swagger after you run appclication add the following to URL in the browser: 
**/swagger-ui/index.html**
To view it as a json add 
**/v3/api-docs**
To download it as a yaml file add
**/v3/api-docs.yaml**
Examples:
http://localhost:8080/swagger-ui/index.html
http://localhost:8080/v3/api-docs
http://localhost:8080/v3/api-docs.yaml

2022-02-23 11:02 UTC, jasokolowska requested changes
Klasa TeamMember oraz odnoszące sie do niej metody w Controllerze do usunięcia

2022-02-23 14:07 UTC, jasokolowska commented on src/main/java/com/intive/patronage22eganortap/web/controller/HelloTeamController.java
> +    }
tą metodę public TeamMember create tez musisz usunac, bo nie ma klasy TeamMember

2022-02-23 14:46 UTC, Pawel-Koz commented on src/main/java/com/intive/patronage22eganortap/web/controller/HelloTeamController.java
> +    }
wybrałem tą metodę jako przykład bo więcej się w niej dzieje w porównaniu z metodą hello(). Poczekam z tym na leaderów co powiedzą

2022-02-24 08:08 UTC, sayuuri requested changes
Wydaje mi się że usunięcie klasy TeamMember, zbytnio namieszało, i controller nie będzie działał poprawnie, bo w HelloTeamController zapewno będzie problem w linii 34.

2022-02-24 09:44 UTC, Pawel-Koz commented on src/main/java/com/intive/patronage22eganortap/web/controller/HelloTeamController.java
> +                            schema = @Schema(implementation = TeamMember.class))),
Moim zamierzeniem było pokazanie przykładu adnotacji na przykładzie na którym jak najwięcej się dzieje. Gdzie właśnie mamy jako content json, schema - odwołanie się do odpowiedniej klasy. W takiej postaci (bez klasy "TeamMember") jest to  tylko i  wyłącznie jako szablon do opisywania przyszłych endpointów.

2022-02-24 12:15 UTC, Pawel-Koz commented on src/main/java/com/intive/patronage22eganortap/web/controller/HelloTeamController.java
> +                            schema = @Schema(implementation = TeamMember.class))),
Ja to po prostu zakomentuję i możemy się umówić, że pierwsza osoba która bedzie tworzyc enpointy do naszej aplikacji i je opisywac, usunie tą zakomentowaną metodę

2022-02-25 10:24 UTC, sayuuri approved these changes

2022-02-25 13:17 UTC, jasokolowska commented on pom.xml
> +        </dependency>
wiem, ze to drobiazg, ale tutaj (springdoc-openapi-webmvc-core) tez bym też dodala .version, zeby zachowac takie samo formatowanie

2022-02-25 18:34 UTC, Pawel-Koz commented on src/main/java/com/intive/patronage22eganortap/web/controller/HelloTeamController.java
> +import io.swagger.v3.oas.annotations.responses.ApiResponses;
which one exactly?

2022-02-25 19:21 UTC, jasokolowska approved these changes
Looks fine - TeamMember class and controllers methods which refers to this class should be removed after real endpoint implementation

2022-02-27 11:36 UTC, doomedcat17 approved these changes
looks ok

2022-02-28 13:10 UTC, eveento commented on pom.xml
> +        <springdoc-openapi-data-rest.version>1.6.6</springdoc-openapi-data-rest.version>
wszedzie jest ta sama wersja dlaczego?

2022-02-28 13:10 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/web/controller/HelloTeamController.java
> +    private static final String GROUP_TAG = "TeamMembers";
nazwa zmiennej nic nie mowi

2022-02-28 13:10 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/web/controller/HelloTeamController.java
> +    public static List<TeamMember> createList() {
do usuniecia

2022-02-28 13:10 UTC, eveento commented on src/main/resources/application.properties
> +#springdoc.api-docs.path=/api-docs
jesli nie potrzebujemy zadnej konfiguracji to po co to tutaj jest? zcy aby na pewno niczego nie potrzebujemy konfigurowac?

2022-02-28 13:10 UTC, eveento commented on src/main/java/com/intive/patronage22eganortap/web/controller/HelloTeamController.java
> +    public TeamMember create(@Valid @RequestBody @io.swagger.v3.oas.annotations.parameters.RequestBody TeamMember member) {
zle napisany endpoint, mozna to wszystko przeniesc na endpoin hello. w takiej postaci nie potrzebujemy 2

2022-03-01 14:01 UTC, Pawel-Koz commented on pom.xml
> +        <springdoc-openapi-data-rest.version>1.6.6</springdoc-openapi-data-rest.version>
ściągnąłem ze strony springdoc, te same wersje na maven repo, są to najnowsze wersje

2022-03-02 09:12 UTC, eveento commented on pom.xml
> +        <springdoc-openapi-data-rest.version>1.6.6</springdoc-openapi-data-rest.version>
czy nie mozna uzyc jednej zmiennej skoro i tak wersja sa te same?

2022-03-02 15:17 UTC, merged